labels:
  - name: "type:bug"
    color: "d73a4a"
    description: "Something is not working"
  - name: "type:enhancement"
    color: "a2eeef"
    description: "New feature or request"
  - name: "scope:infra"
    color: "5319e7"
    description: "Infrastructure-related"
  - name: "scope:llm"
    color: "0e8a16"
    description: "LLM prompt / model changes"
  - name: "good-first-issue"
    color: "7057ff"
    description: "Good for newcomers"
  - name: "documentation"
    color: "0075ca"
    description: "Improvements or additions to documentation"