name: CI
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    environment: CI/CD
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - run: yarn install --immutable
      - run: yarn lint
      - run: yarn test --coverage
      - name: Restore Turbo build cache
        uses: actions/cache@v3
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ hashFiles('**/yarn.lock') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-${{ hashFiles('**/yarn.lock') }}-
            ${{ runner.os }}-turbo-
      - run: yarn turbo run build
