name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: CI/CD

    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - run: yarn install --immutable

      - name: Restore Turbo build cache
        uses: actions/cache@v3
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ hashFiles('**/yarn.lock') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-${{ hashFiles('**/yarn.lock') }}-
            ${{ runner.os }}-turbo-

      - run: yarn turbo run build --filter=@parlay/edge-miner

      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}

      - name: Install serverless CLI support
        run: doctl serverless install

      - name: Connect to Functions namespace
        run: doctl serverless connect fn-a235d324-5351-479d-bcec-cddaa8bccac5

      - name: Create environment file
        run: |
          mkdir -p apps/edge-miner/dist
          cat <<EOF > apps/edge-miner/dist/.env
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          ODDS_API_KEY=${{ secrets.ODDS_API_KEY }}
          TWILIO_SID=${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN=${{ secrets.TWILIO_TOKEN }}
          TWILIO_FROM=${{ secrets.TWILIO_FROM }}
          TWILIO_TO=${{ secrets.TWILIO_TO }}
          EOF

      - name: Deploy serverless function
        run: |
          doctl serverless deploy apps/edge-miner/dist \
            --env apps/edge-miner/dist/.env \
            --remote-build