name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: CI/CD
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - run: yarn install --immutable
      - name: Restore Turbo build cache
        uses: actions/cache@v3
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ hashFiles('**/yarn.lock') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-${{ hashFiles('**/yarn.lock') }}-
            ${{ runner.os }}-turbo-
      - run: yarn turbo run build --filter=apps/edge-miner
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}
      - run: |
          doctl serverless deploy apps/edge-miner/dist \
            --env OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            --env ODDS_API_KEY=${{ secrets.ODDS_API_KEY }} \
            --env TWILIO_SID=${{ secrets.TWILIO_SID }} \
            --env TWILIO_TOKEN=${{ secrets.TWILIO_TOKEN }} \
            --env TWILIO_FROM=${{ secrets.TWILIO_FROM }} \
            --env TWILIO_TO=${{ secrets.TWILIO_TO }} \
            --remote-build
